### ISSUE TITLE
v1 compatibility ?

### ISSUE THREAD

**Issue by stephanepericat** [smbddha/SGDSS#1]
Hi,

do you have any plans to make these plugins compatible with Rack 1.x ?

Cheers,
Stephane

**Comment by stephanepericat** [comment]
hi @smbddha ,

I opened a PR with the updated code: https://github.com/smbddha/sb-StochKit/pull/2

Cheers,
Stephane

**Comment by smbddha** [comment]
Hey @stephanepericat,

Thanks a bunch! Haven't had time to make the changes myself. I'll look over the pr today.

-Sam

**Comment by stephanepericat** [comment]
@smbddha ,

I noticed the "mirr" switch in Grandy doesn't seem to work as expected... so you might wanna look into that. For the rest, it seems to run like the old plugins :)

FYI it is based on this version of the Rack SDK https://vcvrack.com/downloads/Rack-SDK-1.dev.b4bd09a.zip . If you check out my branch, you should download this zip and extract it under `dep/Rack-SDK` . Then you can run `sh install.sh` (mac or linux) and it will install it in the `plugins-v1` folder of Rack for you :)

**Comment by stephanepericat** [comment]
Update: looks like i fixed the "mirr" issue I reported in this commit https://github.com/smbddha/sb-StochKit/pull/2/commits/95482031d253c18a3a5856351e771203a68c6d77

**Comment by smbddha** [comment]
@stephanepericat, amazing! thanks again for the work. I've incorporated your pr
